import Header from '@/components/header';
import NavBar from '@/components/navbar';
import ScreenIndicator from '@/components/screen-indicator';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const raveoSans = localFont({
  src: './fonts/RaveoVF.woff2',
  variable: '--font-sans',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: '%s | Jaypal Sapara',
    default: 'Jaypal Sapara',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('h-full', 'antialiased', geistMono.variable, 'font-sans', raveoSans.variable)}>
      <body className="flex min-h-full flex-col">
        <Header />
        <NavBar />
        {children}

        <ScreenIndicator />
      </body>
    </html>
  );
}
